### ISSUE TITLE
ModuleNotFoundError: No module named 'tempest'

### ISSUE THREAD

**Issue by SebNik1** [git-artes/gr-tempest#10]
Dear Federico, thank you for sharing your implementation! I am struggeling getting it to work on latest kali linux though, I was able to build it (long struggle installing mpir) but not in gnuradio it says "tempest ModuleNotFound". I would really appreciate your help. Also I will try to provide further information you need. Thank you very much in advance!

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/kali/gr-tempest/examples/automatic_tempest_example.grc"
>>> Done

Generating: '/home/kali/gr-tempest/examples/automatic_tempest_example.py'

Executing: /usr/bin/python3 -u /home/kali/gr-tempest/examples/automatic_tempest_example.py

Traceback (most recent call last):
  File "/home/kali/gr-tempest/examples/automatic_tempest_example.py", line 36, in <module>
    import tempest
ModuleNotFoundError: No module named 'tempest'

>>> Done (return code 1)

**Comment by git-artes** [comment]
Thanks for the interest. Do you have the pythonpath set correctly?

**Comment by SebNik1** [comment]
Thank you very much for the quick reply. Can you please give me a hint in what context or what step you mean? It's the first time I use gnuradio, I might have made an error there if I missed to setup something.

**Comment by git-artes** [comment]
If you are using it for the first time maybe you can use the Docker I've prepared: https://github.com/git-artes/docker-gnuradio. 
Anyway, the error you got means that Python is not finding the tempest module, which is installed by default on /usr/local/lib/python3/dist-packages. Check if you have it there.
If you do, in Ubuntu 20.04 (I'm not familiar with Kali) you should simply write: 
`export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3/dist-packages`
in a terminal and then run the companion. If you want to avoid always writing the above command, you may include it in your home's .bashrc or system wide in /etc/environment.

**Comment by SebNik1** [comment]
Thank you, I will check that and let you know!

**Comment by SebNik1** [comment]
Thank you for your advice, I first try to fix a self-installation and setting the python path worked for finding the module. Now I get another error:

Generating: '/home/kali/gr-tempest/examples/semi_automatic_tempest_example.py'

Executing: /usr/bin/python3 -u /home/kali/gr-tempest/examples/semi_automatic_tempest_example.py

SDL screen_mode 32 bits-per-pixel
SDL overlay_mode 842094169 
d_max_deviation_px: 20
[TEMPEST] Setting Htotal to 708 and Vtotal to 806 in fine sampling synchronization block.
gr::log :ERROR: file_source0 - /home/gnuradio/persistent/grabacion_HDMI.dat: No such file or directory
Traceback (most recent call last):
  File "/home/kali/gr-tempest/examples/semi_automatic_tempest_example.py", line 436, in <module>
    main()
  File "/home/kali/gr-tempest/examples/semi_automatic_tempest_example.py", line 412, in main
    tb = top_block_cls()
  File "/home/kali/gr-tempest/examples/semi_automatic_tempest_example.py", line 180, in __init__
    self.blocks_file_source_0 = blocks.file_source(gr.sizeof_gr_complex*1, '/home/gnuradio/persistent/grabacion_HDMI.dat', True, 0, 0)
  File "/usr/lib/python3/dist-packages/gnuradio/blocks/blocks_swig0.py", line 1008, in make
    return _blocks_swig0.file_source_make(itemsize, filename, repeat, offset, len)
RuntimeError: can't open file

>>> Done (return code 1)

I wasnt able to locate the missing files in the package. I also tried reinstalling gnuradio but it did not help. Do you happen to know more? Thank you in advance!

**Comment by git-artes** [comment]
You should download the files from the project's website https://iie.fing.edu.uy/investigacion/grupos/artes/es/proyectos/espionaje-por-emisiones-electromagneticas/ (read the README) and point the file source to that file.
I'll close this as your original problem was solved.
best
