### ISSUE TITLE
Make error on latest Arch Linux

### ISSUE THREAD

**Issue by aocard** [git-artes/gr-tempest#14]
Hello!

Trying to build on latest Arch Linux. This is the output of "make":

[ 12%] Building CXX object lib/CMakeFiles/gnuradio-tempest.dir/sampling_synchronization_impl.cc.o
/home/user/Files/gr-tempest/lib/sampling_synchronization_impl.cc: In static member function ‘static gr::tempest::sampling_synchronization::sptr gr::tempest::sampling_synchronization::make(int, double)’:
/home/user/Files/gr-tempest/lib/sampling_synchronization_impl.cc:42:9: error: could not convert ‘gnuradio::get_initial_sptr(T*) [with T = gr::tempest::sampling_synchronization_impl]()’ from ‘std::shared_ptr<gr::tempest::sampling_synchronization_impl>’ to ‘gr::tempest::sampling_synchronization::sptr’ {aka ‘boost::shared_ptr<gr::tempest::sampling_synchronization>’}
   41 |       return gnuradio::get_initial_sptr
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~
   42 |         (new sampling_synchronization_impl(Htotal, manual_correction));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         |
      |         std::shared_ptr<gr::tempest::sampling_synchronization_impl>
make[2]: *** [lib/CMakeFiles/gnuradio-tempest.dir/build.make:76: lib/CMakeFiles/gnuradio-tempest.dir/sampling_synchronization_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:233: lib/CMakeFiles/gnuradio-tempest.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Any help is appreciated (:

**Comment by git-artes** [comment]
Mmmm seems like a problem of GNU Radio. Note that gr-tempest works for 3.8 or 3.7 only. Maybe you have 3.9?

**Comment by aocard** [comment]
Yes, that was it. Rebuilt GNURadio, this tive v3.8, and managed to compile. Thank you.
