### ISSUE TITLE
Source of "30M_tv_g50_v2.dat" file

### ISSUE THREAD

**Issue by DeepFriedJif** [git-artes/gr-tempest#25]
Hello, I am attempting to run the **manual_tempest_example.grc** after successfully building the code and installing after following the README. However, once I launch gnuradio-companion and try to execute the aforementioned .grc I get an error because the File Source module is looking for a file that is not present, namely the "**30M_tv_g50_v2.dat**" file. Apologies for my ignorance, but I was unable to locate the source file in the repo, or find and obvious references to sources or downloads to it. Could you please tell me where I can find this file? 

Thank you for your work keeping this project alive! I am new to hobby RF and SDR work but I am trying to jump in and experience some of this amazing tech. 

Attached is an image of the grc output. 
![image](https://github.com/git-artes/gr-tempest/assets/28983900/f71c10d7-5666-47c4-8d05-1d11169d7df2)

**Comment by git-artes** [comment]
Thanks for the interest! You may download these recordiings from the project's website. See the README for its URL.

**Comment by DeepFriedJif** [comment]
Thank you for the swift reply! I see the download links on the website and will get the files from there.

**Comment by git-artes** [comment]
Hi,
The link to the project's website is on the README. I'll paste it here anyway: https://iie.fing.edu.uy/investigacion/grupos/artes/es/proyectos/espionaje-por-emisiones-electromagneticas/
It's in spanish, but it should be easy to find the "Recordings" section.
best
