### ISSUE TITLE
grc not starting

### ISSUE THREAD

**Issue by fe8769a** [git-artes/gr-tempest#5]
hello

Thanks for volks correction 

Here is a new one 

SDR is ETTUS b210 working fine with gqrx, gr-gsm , ...

when starting automatic_tempest_example.grc here is the error

lunbuntu from dragon_OS suite 18.04

<<< Welcome to GNU Radio Companion 3.7.11 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/xxxxxx/gr-tempest/examples/automatic_tempest_example.grc"
>>> Done

Generating: '/home/xxxxxx/gr-tempest/examples/automatic_tempest_example.py'

Executing: /usr/bin/python -u /home/xxxxxx/gr-tempest/examples/automatic_tempest_example.py

QApplication: invalid style override passed, ignoring it.
SDL screen_mode 32 bits-per-pixel
SDL overlay_mode 842094169 
Traceback (most recent call last):
  File "/home/xxxxxx/gr-tempest/examples/automatic_tempest_example.py", line 323, in <module>
    main()
  File "/home/xxxxxx/gr-tempest/examples/automatic_tempest_example.py", line 311, in main
    tb = top_block_cls()
  File "/home/xxxxxx/gr-tempest/examples/automatic_tempest_example.py", line 105, in __init__
    self.tempest_sampling_synchronization_0 = tempest.sampling_synchronization(interpolatedHsize, 0)
AttributeError: 'module' object has no attribute 'sampling_synchronization'

>>> Done

thanks

**Comment by git-artes** [comment]
Hi, 
Did you install swig? This error, as indicated in the FAQ, is typically generated by a non-installed swig. You may also have to set PYTHONPATH to point to dist-packages folder (e.g. in Python 2.7 /usr/local/lib/python2.7/dist-packages).
best

**Comment by fe8769a** [comment]
I'm lost with Python ,some programs are working with python3 (eg imsi-catcher) other with python

Python
python
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

Swig
swig -version

SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

I did :+1: 

export PYTHONPATH=/usr/local/lib/python2.7/dist-packages

Still same error 

thanks for help

**Comment by git-artes** [comment]
Was swig installed before compiling? Did you `sudo ldconfig`?

**Comment by Andreas237** [comment]
@git-artes: suggesting you close this issue as it appears dead
