### ISSUE TITLE
Using omnidirectional antenna 

### ISSUE THREAD

**Issue by bmarjanovic** [git-artes/gr-tempest#7]
First, thanks for a really interesting project. 
I've managed to build and run the example with no issues related to the project code. 
I'm running gnuradio 3.7.14.0 and using ettus b200mini with RF Solutions Antenna ANT-4WHIP3H-SMA, Whip SMA 433MHz. The reason for the details about the antenna is because my question is regarding the antenna.
The video shows what seems like directional antenna. Would you expect omnidirectional to work as well? 

We are trying to use it on both VGA and HDMI cables but with no luck. The monitors in question have fairly high resolution. We did try lowering the resolution but it made no difference. I'm not sure if lowering the monitor resolution on the windows display settings has any effect on signal in HDMI cable. 
We tried two monitor: 
- 1920x1080 at 60Hz
- 2560 x 1440 at 60Hz
Do you have any suggestions what we might try?

**Comment by git-artes** [comment]
Hi, 
Naturally, the emitted power is very low, so a good antenna and fiddling with the SDR's gain helps. If you have nothing but a whip antenna, you may try using a cheap adapter in the VGA cable (such as https://www.ebay.com/itm/VGA-Y-Splitter-Cable-8-Long-DB15-HD-Male-to-2X-DB15HD-female-VGA-Y-splitter-/272839405718?_trksid=p2385738.m4383.l4275.c10). With that you should receive a fairly good signal (see https://youtu.be/qrplI0k8XbI, where I'm receiving with the antenna that comes with the rtl-sdr bundle).
best

**Comment by bmarjanovic** [comment]
Thanks for the response. 
A bit of fiddling got me there. My image is not as good as the one in the  above video but is reasonable. I used manual example with hackrf with the same antenna and, as per your suggestion played with parameters (gain, resolutions and corrections etc)
I'm yet to read the thesis - maybe should have done that first to understand the math behind it - might have helped while fiddling with parameters. 
Thanks again
